import numpy as np
np.savetxt(
    'mydata.csv',           
    imgarr,                
    fmt='%.2f',            
    delimiter=',',         
    newline='\n',           
    footer='end of file',   
    comments='# ',         
    header='Data generated by numpy')     